//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_tasks
    {
        public string UserName { get; set; }
        public int Task_id { get; set; }
        public string Title { get; set; }
        public string Task_Description { get; set; }
        public string Task_Status { get; set; }
    }
}
